name: Coco Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install Just
        run: cargo install just

      - name: Build
        run: ${{matrix.ENV_VARS}} cargo build --verbose --release

      - name: Build Debug for Testing
        run: ${{matrix.ENV_VARS}} cargo build

      - name: Run unit tests
        run: ${{matrix.ENV_VARS}} just tests

      - name: Run e2e
        run: ${{matrix.ENV_VARS}} just e2e
